qca-backport:Update backports to the ath10k.git TOT
wil6210(11ad) patches has been merged in upstream, so
updated backport to tot of ath-qca branch of ath.git

*updated wil6210(11ad) firmware file name from wil6210
.board to wil6210.brd, as per wil6210 driver

Change-Id: If006af7d496374041e36834cf9a671a61a9d0f3e
Signed-off-by: Ram Chandra Jangir <rjangi@codeaurora.org>

diff --git a/qca-backports/patches/001-fix_build.patch b/qca-backports/patches/001-fix_build.patch
--- a/qca-backports/patches/001-fix_build.patch
+++ b/qca-backports/patches/001-fix_build.patch
@@ -1,6 +1,6 @@
 --- a/Makefile
 +++ b/Makefile
-@@ -19,6 +19,7 @@ KLIB_BUILD ?= $(KLIB)/build/
+@@ -19,6 +19,7 @@
  KERNEL_CONFIG := $(KLIB_BUILD)/.config
  KERNEL_MAKEFILE := $(KLIB_BUILD)/Makefile
  CONFIG_MD5 := $(shell md5sum $(KERNEL_CONFIG) 2>/dev/null | sed 's/\s.*//')
@@ -8,7 +8,7 @@
  
  export KLIB KLIB_BUILD BACKPORT_DIR KMODDIR KMODPATH_ARG
  
-@@ -36,7 +37,8 @@ mrproper:
+@@ -36,7 +37,8 @@
  	@rm -f .kernel_config_md5 Kconfig.versions Kconfig.kernel
  	@rm -f backport-include/backport/autoconf.h
  
@@ -18,7 +18,7 @@
  	@set -e ; test -f .local-symbols || (						\
  	echo "/--------------"								;\
  	echo "| You shouldn't run make in the backports tree, but only in"		;\
-@@ -60,56 +62,60 @@ mrproper:
+@@ -60,57 +62,60 @@
  	echo "| (that isn't currently running.)"					;\
  	echo "\\--"									;\
  	false)
@@ -47,11 +47,12 @@
 -			done								\
 -		) > Kconfig.kernel							;\
 -		kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
--			sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')			;\
+-			sed 's/^\(\([3-4]\|2\.6\)\.[0-9]\+\).*/\1/;t;d')		;\
 -		test "$$kver" != "" || echo "Kernel version parse failed!"		;\
 -		test "$$kver" != ""							;\
 -		kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
--		kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"				;\
+-		kvers="$$kvers $$(seq 0 19 | sed 's/^/3./')"				;\
+-		kvers="$$kvers $$(seq 0 99 | sed 's/^/4./')"				;\
 -		print=0									;\
 -		for v in $$kvers ; do							\
 -			if [ "$$print" = "1" ] ; then					\
@@ -77,51 +78,51 @@
 +
 +Kconfig.kernel: $(STAMP_KERNEL_CONFIG) .local-symbols
 +	@printf "Generating local configuration database from kernel ..."
-+	@grep -v -f .local-symbols $(KERNEL_CONFIG) | grep = | (			\
-+		while read l ; do						\
-+			if [ "$${l:0:7}" != "CONFIG_" ] ; then			\
-+				continue					;\
-+			fi							;\
-+			l=$${l:7}						;\
-+			n=$${l%%=*}						;\
-+			v=$${l#*=}						;\
-+			if [ "$$v" = "m" ] ; then				\
-+				echo config $$n					;\
-+				echo '    tristate' 				;\
-+			elif [ "$$v" = "y" ] ; then				\
-+				echo config $$n					;\
-+				echo '    bool'					;\
-+			else							\
-+				continue					;\
-+			fi							;\
-+			echo "    default $$v"					;\
-+			echo ""							;\
-+		done								\
++	@grep -v -f .local-symbols $(KERNEL_CONFIG) | grep = | (                        \
++		while read l ; do                                               \
++			if [ "$${l:0:7}" != "CONFIG_" ] ; then                  \
++				continue                                        ;\
++			fi                                                      ;\
++			l=$${l:7}                                               ;\
++			n=$${l%%=*}                                             ;\
++			v=$${l#*=}                                              ;\
++			if [ "$$v" = "m" ] ; then                               \
++				echo config $$n                                 ;\
++				echo '    tristate'                             ;\
++			elif [ "$$v" = "y" ] ; then                             \
++				echo config $$n                                 ;\
++				echo '    bool'                                 ;\
++			else                                                    \
++				continue                                        ;\
++			fi                                                      ;\
++			echo "    default $$v"                                  ;\
++			echo ""                                                 ;\
++		done                                                            \
 +	) > $@
 +	@echo " done."
 +
 +Kconfig.versions: Kconfig.kernel
-+	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
-+		sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')			;\
-+	test "$$kver" != "" || echo "Kernel version parse failed!"		;\
-+	test "$$kver" != ""							;\
-+	kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
-+	kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"				;\
-+	print=0									;\
-+	for v in $$kvers ; do							\
-+		if [ "$$print" = "1" ] ; then					\
-+			echo config KERNEL_$$(echo $$v | tr . _)		;\
-+			echo "    def_bool y"					;\
-+		fi								;\
-+		if [ "$$v" = "$$kver" ] ; then print=1 ; fi			;\
++	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |  \
++		sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')                    ;\
++	test "$$kver" != "" || echo "Kernel version parse failed!"              ;\
++	test "$$kver" != ""                                                     ;\
++	kvers="$$(seq 14 39 | sed 's/^/2.6./')"                                 ;\
++	kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"                            ;\
++	print=0                                                                 ;\
++	for v in $$kvers ; do                                                   \
++		if [ "$$print" = "1" ] ; then                                   \
++			echo config KERNEL_$$(echo $$v | tr . _)                ;\
++			echo "    def_bool y"                                   ;\
++		fi                                                              ;\
++		if [ "$$v" = "$$kver" ] ; then print=1 ; fi                     ;\
 +	done > $@
-+	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
-+	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) | 			\
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
-+	for v in $$(seq 0 $$RHEL_MINOR) ; do 					\
-+		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v		;\
-+		echo "    def_bool y"						;\
++	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) |                  \
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
++	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) |                   \
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
++	for v in $$(seq 0 $$RHEL_MINOR) ; do                                    \
++		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v             ;\
++		echo "    def_bool y"                                           ;\
 +	done >> $@
 +
 +.DEFAULT:
@@ -131,7 +132,7 @@
  .PHONY: defconfig-help
 --- a/Makefile.real
 +++ b/Makefile.real
-@@ -59,7 +59,7 @@ defconfig-%::
+@@ -59,7 +59,7 @@
  
  backport-include/backport/autoconf.h: .config Kconfig.versions Kconfig.kernel
  	@$(MAKE) oldconfig
@@ -140,7 +141,7 @@
  	@grep -f .local-symbols .config | (				\
  		echo "#ifndef COMPAT_AUTOCONF_INCLUDED"			;\
  		echo "#define COMPAT_AUTOCONF_INCLUDED"			;\
-@@ -80,7 +80,12 @@ backport-include/backport/autoconf.h: .c
+@@ -80,7 +80,12 @@
  			esac						;\
  		done							;\
  		echo "#endif /* COMPAT_AUTOCONF_INCLUDED */"		;\
