mac80211: Upgrade the package to 20150909
Change-Id: Ic36a19e69be407912833c01b51789c6b704f8af5
Signed-off-by: Vasanthakumar Thiagarajan <vthiagar@codeaurora.org>

diff --git a/mac80211/patches/001-fix_build.patch b/mac80211/patches/001-fix_build.patch
--- a/mac80211/patches/001-fix_build.patch
+++ b/mac80211/patches/001-fix_build.patch
@@ -1,5 +1,14 @@
 --- a/Makefile
 +++ b/Makefile
+@@ -5,7 +5,7 @@
+ ifeq ($(KERNELRELEASE),)
+ 
+ MAKEFLAGS += --no-print-directory
+-SHELL := /bin/bash
++SHELL := /usr/bin/env bash
+ BACKPORT_DIR := $(shell pwd)
+ 
+ KMODDIR ?= updates
 @@ -19,6 +19,7 @@ KLIB_BUILD ?= $(KLIB)/build/
  KERNEL_CONFIG := $(KLIB_BUILD)/.config
  KERNEL_MAKEFILE := $(KLIB_BUILD)/Makefile
@@ -18,7 +27,7 @@
  	@set -e ; test -f .local-symbols || (						\
  	echo "/--------------"								;\
  	echo "| You shouldn't run make in the backports tree, but only in"		;\
-@@ -60,56 +62,60 @@ mrproper:
+@@ -60,57 +62,61 @@ mrproper:
  	echo "| (that isn't currently running.)"					;\
  	echo "\\--"									;\
  	false)
@@ -47,11 +56,12 @@
 -			done								\
 -		) > Kconfig.kernel							;\
 -		kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
--			sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')			;\
+-			sed 's/^\(\([3-4]\|2\.6\)\.[0-9]\+\).*/\1/;t;d')		;\
 -		test "$$kver" != "" || echo "Kernel version parse failed!"		;\
 -		test "$$kver" != ""							;\
 -		kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
--		kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"				;\
+-		kvers="$$kvers $$(seq 0 19 | sed 's/^/3./')"				;\
+-		kvers="$$kvers $$(seq 0 99 | sed 's/^/4./')"				;\
 -		print=0									;\
 -		for v in $$kvers ; do							\
 -			if [ "$$print" = "1" ] ; then					\
@@ -77,51 +87,52 @@
 +
 +Kconfig.kernel: $(STAMP_KERNEL_CONFIG) .local-symbols
 +	@printf "Generating local configuration database from kernel ..."
-+	@grep -v -f .local-symbols $(KERNEL_CONFIG) | grep = | (			\
-+		while read l ; do						\
-+			if [ "$${l:0:7}" != "CONFIG_" ] ; then			\
-+				continue					;\
-+			fi							;\
-+			l=$${l:7}						;\
-+			n=$${l%%=*}						;\
-+			v=$${l#*=}						;\
-+			if [ "$$v" = "m" ] ; then				\
-+				echo config $$n					;\
-+				echo '    tristate' 				;\
-+			elif [ "$$v" = "y" ] ; then				\
-+				echo config $$n					;\
-+				echo '    bool'					;\
-+			else							\
-+				continue					;\
-+			fi							;\
-+			echo "    default $$v"					;\
-+			echo ""							;\
-+		done								\
++	@grep -v -f .local-symbols $(KERNEL_CONFIG) | grep = | (                        \
++		while read l ; do                                               \
++			if [ "$${l:0:7}" != "CONFIG_" ] ; then                  \
++				continue                                        ;\
++			fi                                                      ;\
++			l=$${l:7}                                               ;\
++			n=$${l%%=*}                                             ;\
++			v=$${l#*=}                                              ;\
++			if [ "$$v" = "m" ] ; then                               \
++				echo config $$n                                 ;\
++				echo '    tristate'                             ;\
++			elif [ "$$v" = "y" ] ; then                             \
++				echo config $$n                                 ;\
++				echo '    bool'                                 ;\
++			else                                                    \
++				continue                                        ;\
++			fi                                                      ;\
++			echo "    default $$v"                                  ;\
++			echo ""                                                 ;\
++		done                                                            \
 +	) > $@
 +	@echo " done."
 +
 +Kconfig.versions: Kconfig.kernel
-+	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
-+		sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')			;\
-+	test "$$kver" != "" || echo "Kernel version parse failed!"		;\
-+	test "$$kver" != ""							;\
-+	kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
-+	kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"				;\
-+	print=0									;\
-+	for v in $$kvers ; do							\
-+		if [ "$$print" = "1" ] ; then					\
-+			echo config KERNEL_$$(echo $$v | tr . _)		;\
-+			echo "    def_bool y"					;\
-+		fi								;\
-+		if [ "$$v" = "$$kver" ] ; then print=1 ; fi			;\
++	@kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |  \
++		sed 's/^\(\([3-4]\|2\.6\)\.[0-9]\+\).*/\1/;t;d')                    ;\
++	test "$$kver" != "" || echo "Kernel version parse failed!"              ;\
++	test "$$kver" != ""                                                     ;\
++	kvers="$$(seq 14 39 | sed 's/^/2.6./')"                                 ;\
++	kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"                            ;\
++	kvers="$$kvers $$(seq 0 99 | sed 's/^/4./')"				;\
++	print=0                                                                 ;\
++	for v in $$kvers ; do                                                   \
++		if [ "$$print" = "1" ] ; then                                   \
++			echo config KERNEL_$$(echo $$v | tr . _)        ;\
++			echo "    def_bool y"                                   ;\
++		fi                                                              ;\
++		if [ "$$v" = "$$kver" ] ; then print=1 ; fi                     ;\
 +	done > $@
-+	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
-+	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) | 			\
-+				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
-+	for v in $$(seq 0 $$RHEL_MINOR) ; do 					\
-+		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v		;\
-+		echo "    def_bool y"						;\
++	@RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) |                  \
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
++	RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) |                   \
++				sed 's/.*=\s*\([0-9]*\)/\1/;t;d')               ;\
++	for v in $$(seq 0 $$RHEL_MINOR) ; do                                    \
++		echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v             ;\
++		echo "    def_bool y"                                           ;\
 +	done >> $@
 +
 +.DEFAULT:
